name: Hello-test

on: push

jobs: 
    hello-world-job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4
          - run: echo "$(Hello, Test!)"
